### PR TITLE
Basic Development dependencies in readme

### PR DESCRIPTION
**Pull request by piotr-iohk**
Some things I've stumbled on and thought it might be good to document.

### CODE REVIEW

**Comment by joaosreis** [comment]
I think we should actually remove the VSCode workspace settings from the repo. I think it's not a good practice. We could however include a `.vscode/extensions.json` with recommended project extensions.
https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions

**Comment by harrysolovay** [comment]
I agree with @joaosreis –– also, let's place any development-related changes in the [`CONTRIBUTING.md`'s environment setup](https://github.com/MinaFoundation/MinaMesh/blob/main/CONTRIBUTING.md#environment-setup), not the readme.

**Comment by harrysolovay** [comment]
These dependencies are already documented there. Re. the vscode extensions, we could have a `.vscode/extensions.json` with a `recommendations` field. Created #39 to track it, but it's not a priority. Closing for now.

**Comment by piotr-iohk** [comment]
> These dependencies are already documented there. Re. the vscode extensions, we could have a `.vscode/extensions.json` with a `recommendations` field. Created #39 to track it, but it's not a priority. Closing for now.

I missed that, thanks.

**Pull request closed without merging**
